version: '3.8'

services:
  # Servi√ßo do PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: my-bank-postgres-card
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms-card
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: